[blue_loadout]
team_color_id = 34
custom_color_id = 54
car_id = 0
decal_id = 5432
wheels_id = 1580
boost_id = 1336
antenna_id = 0
hat_id = 0
paint_finish_id = 0
custom_finish_id = 0
engine_audio_id = 0
trails_id = 1974
goal_explosion_id = 3763

[orange_loadout]
team_color_id = 18
custom_color_id = 25
car_id = 0
decal_id = 5432
wheels_id = 1580
boost_id = 1336
antenna_id = 0
hat_id = 0
paint_finish_id = 0
custom_finish_id = 0
engine_audio_id = 0
trails_id = 1974
goal_explosion_id = 3763

[blue_loadout.paint]
car_paint_id = 0
decal_paint_id = 0
wheels_paint_id = 12
boost_paint_id = 0
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 0
goal_explosion_paint_id = 11

[orange_loadout.paint]
car_paint_id = 0
decal_paint_id = 0
wheels_paint_id = 12
boost_paint_id = 0
antenna_paint_id = 0
hat_paint_id = 0
trails_paint_id = 0
goal_explosion_paint_id = 11
